server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/imobiliaria?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: leonbpc
  jpa:
    hibernate:
      ddl-auto: update

